#!/bin/bash
echo Start!
cd ..
rm -rf open_testcase
tar zxvf open_testcase.tar.gz
tar zxvf hidden_testcase.tar.gz
tar zxvf student_rpt.tar.gz
cd simulator
make clean
make
echo 1.pipeline1
cp  ../open_testcase/pipeline1/iimage.bin .
cp  ../open_testcase/pipeline1/dimage.bin .
./pipeline
diff snapshot.rpt ../open_testcase/pipeline1/snapshot.rpt
diff error_dump.rpt ../open_testcase/pipeline1/error_dump.rpt
echo ...end
echo 2.pipeline2
cp  ../open_testcase/pipeline2/iimage.bin .
cp  ../open_testcase/pipeline2/dimage.bin .
./pipeline
diff snapshot.rpt ../open_testcase/pipeline2/snapshot.rpt
diff error_dump.rpt ../open_testcase/pipeline2/error_dump.rpt
echo ...end
echo 3.pipeline3
cp  ../open_testcase/pipeline3/iimage.bin .
cp  ../open_testcase/pipeline3/dimage.bin .
./pipeline
diff snapshot.rpt ../open_testcase/pipeline3/snapshot.rpt
diff error_dump.rpt ../open_testcase/pipeline3/error_dump.rpt
echo ...end
echo 4.error
cp  ../open_testcase/error/iimage.bin .
cp  ../open_testcase/error/dimage.bin .
./pipeline
diff snapshot.rpt ../open_testcase/error/snapshot.rpt
diff error_dump.rpt ../open_testcase/error/error_dump.rpt
echo ...end
echo 5.fib_r
cp  ../open_testcase/fib_r/iimage.bin .
cp  ../open_testcase/fib_r/dimage.bin .
./pipeline
diff snapshot.rpt ../open_testcase/fib_r/snapshot.rpt
diff error_dump.rpt ../open_testcase/fib_r/error_dump.rpt
echo ...end

echo 6.bubble_sort
cp  ../hidden_testcase/bubble_sort/iimage.bin .
cp  ../hidden_testcase/bubble_sort/dimage.bin .
./pipeline
diff snapshot.rpt ../hidden_testcase/bubble_sort/snapshot.rpt
diff error_dump.rpt ../hidden_testcase/bubble_sort/error_dump.rpt
echo ...end
echo 7.divide
cp  ../hidden_testcase/divide/iimage.bin .
cp  ../hidden_testcase/divide/dimage.bin .
./pipeline
diff snapshot.rpt ../hidden_testcase/divide/snapshot.rpt
diff error_dump.rpt ../hidden_testcase/divide/error_dump.rpt
echo ...end
echo 8.pipeline4
cp  ../hidden_testcase/pipeline4/iimage.bin .
cp  ../hidden_testcase/pipeline4/dimage.bin .
./pipeline
diff snapshot.rpt ../hidden_testcase/pipeline4/snapshot.rpt
diff error_dump.rpt ../hidden_testcase/pipeline4/error_dump.rpt
echo ...end
echo 9.pipeline5
cp  ../hidden_testcase/pipeline5/iimage.bin .
cp  ../hidden_testcase/pipeline5/dimage.bin .
./pipeline
diff snapshot.rpt ../hidden_testcase/pipeline5/snapshot.rpt 
diff error_dump.rpt ../hidden_testcase/pipeline5/error_dump.rpt
echo ...end

echo 10.own_testcase
cp  ../testcase/iimage.bin .
cp  ../testcase/dimage.bin .
./pipeline
diff snapshot.rpt ../testcase/snapshot.rpt
diff error_dump.rpt ../testcase/error_dump.rpt
echo ...end


make clean
rm snapshot.rpt error_dump.rpt dimage.bin iimage.bin
cd ..
rm -rf open_testcase
rm -rf hidden_testcase
rm -rf student_rpt
echo Done!
